var annotated_dup =
[
    [ "Audio", "namespace_audio.html", [
      [ "SoundBuffer", "class_audio_1_1_sound_buffer.html", "class_audio_1_1_sound_buffer" ],
      [ "SoundFile", "class_audio_1_1_sound_file.html", "class_audio_1_1_sound_file" ],
      [ "VorbisFile", "class_audio_1_1_vorbis_file.html", "class_audio_1_1_vorbis_file" ]
    ] ],
    [ "Component", "namespace_component.html", [
      [ "Camera", "class_component_1_1_camera.html", "class_component_1_1_camera" ],
      [ "DirectionalLight", "class_component_1_1_directional_light.html", "class_component_1_1_directional_light" ],
      [ "Listener", "class_component_1_1_listener.html", "class_component_1_1_listener" ],
      [ "Material", "class_component_1_1_material.html", "class_component_1_1_material" ],
      [ "Mesh", "class_component_1_1_mesh.html", "class_component_1_1_mesh" ],
      [ "PointLight", "class_component_1_1_point_light.html", "class_component_1_1_point_light" ],
      [ "RigidBody", "class_component_1_1_rigid_body.html", "class_component_1_1_rigid_body" ],
      [ "Script", "class_component_1_1_script.html", "class_component_1_1_script" ],
      [ "Shape", "class_component_1_1_shape.html", "class_component_1_1_shape" ],
      [ "SoundSource", "class_component_1_1_sound_source.html", "class_component_1_1_sound_source" ],
      [ "SpotLight", "class_component_1_1_spot_light.html", "class_component_1_1_spot_light" ],
      [ "Sprite", "class_component_1_1_sprite.html", "class_component_1_1_sprite" ],
      [ "SuperComponent", "class_component_1_1_super_component.html", "class_component_1_1_super_component" ],
      [ "Trigger", "class_component_1_1_trigger.html", "class_component_1_1_trigger" ]
    ] ],
    [ "Geometry", "namespace_geometry.html", [
      [ "Cube", "class_geometry_1_1_cube.html", "class_geometry_1_1_cube" ],
      [ "MeshData", "struct_geometry_1_1_mesh_data.html", "struct_geometry_1_1_mesh_data" ],
      [ "Model", "class_geometry_1_1_model.html", "class_geometry_1_1_model" ]
    ] ],
    [ "GUI", "namespace_g_u_i.html", [
      [ "AssetEditor", "class_g_u_i_1_1_asset_editor.html", "class_g_u_i_1_1_asset_editor" ],
      [ "BoxShapeEditor", "class_g_u_i_1_1_box_shape_editor.html", "class_g_u_i_1_1_box_shape_editor" ],
      [ "CapsuleShapeEditor", "class_g_u_i_1_1_capsule_shape_editor.html", "class_g_u_i_1_1_capsule_shape_editor" ],
      [ "ConeShapeEditor", "class_g_u_i_1_1_cone_shape_editor.html", "class_g_u_i_1_1_cone_shape_editor" ],
      [ "CylinderShapeEditor", "class_g_u_i_1_1_cylinder_shape_editor.html", "class_g_u_i_1_1_cylinder_shape_editor" ],
      [ "EntityEditor", "class_g_u_i_1_1_entity_editor.html", "class_g_u_i_1_1_entity_editor" ],
      [ "FileSelector", "class_g_u_i_1_1_file_selector.html", "class_g_u_i_1_1_file_selector" ],
      [ "FolderNameWindow", "class_g_u_i_1_1_folder_name_window.html", "class_g_u_i_1_1_folder_name_window" ],
      [ "GLTFEditor", "class_g_u_i_1_1_g_l_t_f_editor.html", "class_g_u_i_1_1_g_l_t_f_editor" ],
      [ "InputWindow", "class_g_u_i_1_1_input_window.html", "class_g_u_i_1_1_input_window" ],
      [ "IShapeEditor", "class_g_u_i_1_1_i_shape_editor.html", "class_g_u_i_1_1_i_shape_editor" ],
      [ "LogView", "class_g_u_i_1_1_log_view.html", "class_g_u_i_1_1_log_view" ],
      [ "PlaneShapeEditor", "class_g_u_i_1_1_plane_shape_editor.html", "class_g_u_i_1_1_plane_shape_editor" ],
      [ "ProfilingWindow", "class_g_u_i_1_1_profiling_window.html", "class_g_u_i_1_1_profiling_window" ],
      [ "ResourceSelector", "class_g_u_i_1_1_resource_selector.html", "class_g_u_i_1_1_resource_selector" ],
      [ "ResourceView", "class_g_u_i_1_1_resource_view.html", "class_g_u_i_1_1_resource_view" ],
      [ "RigidBodyEditor", "class_g_u_i_1_1_rigid_body_editor.html", "class_g_u_i_1_1_rigid_body_editor" ],
      [ "SavePromptWindow", "class_g_u_i_1_1_save_prompt_window.html", "class_g_u_i_1_1_save_prompt_window" ],
      [ "SceneEditor", "class_g_u_i_1_1_scene_editor.html", "class_g_u_i_1_1_scene_editor" ],
      [ "ScriptEditor", "class_g_u_i_1_1_script_editor.html", "class_g_u_i_1_1_script_editor" ],
      [ "SelectHymnWindow", "class_g_u_i_1_1_select_hymn_window.html", "class_g_u_i_1_1_select_hymn_window" ],
      [ "SettingsWindow", "class_g_u_i_1_1_settings_window.html", "class_g_u_i_1_1_settings_window" ],
      [ "SoundEditor", "class_g_u_i_1_1_sound_editor.html", "class_g_u_i_1_1_sound_editor" ],
      [ "SphereShapeEditor", "class_g_u_i_1_1_sphere_shape_editor.html", "class_g_u_i_1_1_sphere_shape_editor" ],
      [ "TextureEditor", "class_g_u_i_1_1_texture_editor.html", "class_g_u_i_1_1_texture_editor" ],
      [ "TriggerEditor", "class_g_u_i_1_1_trigger_editor.html", "class_g_u_i_1_1_trigger_editor" ]
    ] ],
    [ "Physics", "namespace_physics.html", [
      [ "Shape", "class_physics_1_1_shape.html", "class_physics_1_1_shape" ],
      [ "Trigger", "class_physics_1_1_trigger.html", "class_physics_1_1_trigger" ],
      [ "TriggerObserver", "class_physics_1_1_trigger_observer.html", "class_physics_1_1_trigger_observer" ]
    ] ],
    [ "Profiling", "namespace_profiling.html", [
      [ "Event", "class_profiling_1_1_event.html", "class_profiling_1_1_event" ],
      [ "ProfilingScope", "class_profiling_1_1_profiling_scope.html", "class_profiling_1_1_profiling_scope" ],
      [ "Thread", "class_profiling_1_1_thread.html", "class_profiling_1_1_thread" ],
      [ "Timeline", "class_profiling_1_1_timeline.html", "class_profiling_1_1_timeline" ]
    ] ],
    [ "triggerEvent", "namespacetrigger_event.html", [
      [ "EventStruct", "structtrigger_event_1_1_event_struct.html", "structtrigger_event_1_1_event_struct" ]
    ] ],
    [ "Utility", "namespace_utility.html", [
      [ "LockBox", "class_utility_1_1_lock_box.html", "class_utility_1_1_lock_box" ],
      [ "Queue", "class_utility_1_1_queue.html", "class_utility_1_1_queue" ]
    ] ],
    [ "Video", "namespace_video.html", [
      [ "Geometry", "namespace_video_1_1_geometry.html", [
        [ "VertexType", "namespace_video_1_1_geometry_1_1_vertex_type.html", [
          [ "StaticVertex", "struct_video_1_1_geometry_1_1_vertex_type_1_1_static_vertex.html", "struct_video_1_1_geometry_1_1_vertex_type_1_1_static_vertex" ]
        ] ],
        [ "Geometry2D", "class_video_1_1_geometry_1_1_geometry2_d.html", "class_video_1_1_geometry_1_1_geometry2_d" ],
        [ "Geometry3D", "class_video_1_1_geometry_1_1_geometry3_d.html", "class_video_1_1_geometry_1_1_geometry3_d" ],
        [ "Rectangle", "class_video_1_1_geometry_1_1_rectangle.html", "class_video_1_1_geometry_1_1_rectangle" ]
      ] ],
      [ "AxisAlignedBoundingBox", "class_video_1_1_axis_aligned_bounding_box.html", "class_video_1_1_axis_aligned_bounding_box" ],
      [ "Buffer", "class_video_1_1_buffer.html", "class_video_1_1_buffer" ],
      [ "BufferAllocation", "struct_video_1_1_buffer_allocation.html", "struct_video_1_1_buffer_allocation" ],
      [ "BufferAllocator", "class_video_1_1_buffer_allocator.html", "class_video_1_1_buffer_allocator" ],
      [ "CommandBuffer", "class_video_1_1_command_buffer.html", "class_video_1_1_command_buffer" ],
      [ "ComputePipeline", "class_video_1_1_compute_pipeline.html", "class_video_1_1_compute_pipeline" ],
      [ "DebugDrawing", "class_video_1_1_debug_drawing.html", "class_video_1_1_debug_drawing" ],
      [ "DirectionalLight", "struct_video_1_1_directional_light.html", "struct_video_1_1_directional_light" ],
      [ "Frustum", "class_video_1_1_frustum.html", "class_video_1_1_frustum" ],
      [ "GeometryBinding", "class_video_1_1_geometry_binding.html", "class_video_1_1_geometry_binding" ],
      [ "GraphicsPipeline", "class_video_1_1_graphics_pipeline.html", "class_video_1_1_graphics_pipeline" ],
      [ "Isocahedron", "class_video_1_1_isocahedron.html", "class_video_1_1_isocahedron" ],
      [ "Light", "struct_video_1_1_light.html", "struct_video_1_1_light" ],
      [ "LowLevelRenderer", "class_video_1_1_low_level_renderer.html", "class_video_1_1_low_level_renderer" ],
      [ "OpenGLBuffer", "class_video_1_1_open_g_l_buffer.html", "class_video_1_1_open_g_l_buffer" ],
      [ "OpenGLBufferAllocator", "class_video_1_1_open_g_l_buffer_allocator.html", "class_video_1_1_open_g_l_buffer_allocator" ],
      [ "OpenGLCommandBuffer", "class_video_1_1_open_g_l_command_buffer.html", "class_video_1_1_open_g_l_command_buffer" ],
      [ "OpenGLComputePipeline", "class_video_1_1_open_g_l_compute_pipeline.html", "class_video_1_1_open_g_l_compute_pipeline" ],
      [ "OpenGLGeometryBinding", "class_video_1_1_open_g_l_geometry_binding.html", "class_video_1_1_open_g_l_geometry_binding" ],
      [ "OpenGLGraphicsPipeline", "class_video_1_1_open_g_l_graphics_pipeline.html", "class_video_1_1_open_g_l_graphics_pipeline" ],
      [ "OpenGLRawBuffer", "class_video_1_1_open_g_l_raw_buffer.html", "class_video_1_1_open_g_l_raw_buffer" ],
      [ "OpenGLRenderer", "class_video_1_1_open_g_l_renderer.html", "class_video_1_1_open_g_l_renderer" ],
      [ "OpenGLRenderPass", "class_video_1_1_open_g_l_render_pass.html", "class_video_1_1_open_g_l_render_pass" ],
      [ "OpenGLRenderPassAllocator", "class_video_1_1_open_g_l_render_pass_allocator.html", "class_video_1_1_open_g_l_render_pass_allocator" ],
      [ "OpenGLRenderTargetAllocator", "class_video_1_1_open_g_l_render_target_allocator.html", "class_video_1_1_open_g_l_render_target_allocator" ],
      [ "OpenGLShader", "class_video_1_1_open_g_l_shader.html", "class_video_1_1_open_g_l_shader" ],
      [ "OpenGLShaderProgram", "class_video_1_1_open_g_l_shader_program.html", "class_video_1_1_open_g_l_shader_program" ],
      [ "OpenGLTexture", "class_video_1_1_open_g_l_texture.html", "class_video_1_1_open_g_l_texture" ],
      [ "OpenGLVertexDescription", "class_video_1_1_open_g_l_vertex_description.html", "class_video_1_1_open_g_l_vertex_description" ],
      [ "PostProcessing", "class_video_1_1_post_processing.html", "class_video_1_1_post_processing" ],
      [ "RawBuffer", "class_video_1_1_raw_buffer.html", "class_video_1_1_raw_buffer" ],
      [ "Renderer", "class_video_1_1_renderer.html", "class_video_1_1_renderer" ],
      [ "RenderPass", "class_video_1_1_render_pass.html", "class_video_1_1_render_pass" ],
      [ "RenderPassAllocator", "class_video_1_1_render_pass_allocator.html", "class_video_1_1_render_pass_allocator" ],
      [ "RenderProgram", "class_video_1_1_render_program.html", "class_video_1_1_render_program" ],
      [ "RenderScene", "struct_video_1_1_render_scene.html", "struct_video_1_1_render_scene" ],
      [ "RenderTargetAllocator", "class_video_1_1_render_target_allocator.html", "class_video_1_1_render_target_allocator" ],
      [ "Shader", "class_video_1_1_shader.html", "class_video_1_1_shader" ],
      [ "ShaderProgram", "class_video_1_1_shader_program.html", "class_video_1_1_shader_program" ],
      [ "Sphere", "class_video_1_1_sphere.html", "class_video_1_1_sphere" ],
      [ "SpriteRenderProgram", "class_video_1_1_sprite_render_program.html", "class_video_1_1_sprite_render_program" ],
      [ "StaticRenderProgram", "class_video_1_1_static_render_program.html", "class_video_1_1_static_render_program" ],
      [ "Texture", "class_video_1_1_texture.html", "class_video_1_1_texture" ],
      [ "Texture2D", "class_video_1_1_texture2_d.html", "class_video_1_1_texture2_d" ],
      [ "VertexDescription", "class_video_1_1_vertex_description.html", "class_video_1_1_vertex_description" ],
      [ "VulkanBuffer", "class_video_1_1_vulkan_buffer.html", "class_video_1_1_vulkan_buffer" ],
      [ "VulkanBufferAllocator", "class_video_1_1_vulkan_buffer_allocator.html", "class_video_1_1_vulkan_buffer_allocator" ],
      [ "VulkanCommandBuffer", "class_video_1_1_vulkan_command_buffer.html", "class_video_1_1_vulkan_command_buffer" ],
      [ "VulkanComputePipeline", "class_video_1_1_vulkan_compute_pipeline.html", "class_video_1_1_vulkan_compute_pipeline" ],
      [ "VulkanGeometryBinding", "class_video_1_1_vulkan_geometry_binding.html", "class_video_1_1_vulkan_geometry_binding" ],
      [ "VulkanGraphicsPipeline", "class_video_1_1_vulkan_graphics_pipeline.html", "class_video_1_1_vulkan_graphics_pipeline" ],
      [ "VulkanRawBuffer", "class_video_1_1_vulkan_raw_buffer.html", "class_video_1_1_vulkan_raw_buffer" ],
      [ "VulkanRenderer", "class_video_1_1_vulkan_renderer.html", "class_video_1_1_vulkan_renderer" ],
      [ "VulkanRenderPass", "class_video_1_1_vulkan_render_pass.html", "class_video_1_1_vulkan_render_pass" ],
      [ "VulkanRenderPassAllocator", "class_video_1_1_vulkan_render_pass_allocator.html", "class_video_1_1_vulkan_render_pass_allocator" ],
      [ "VulkanRenderTargetAllocator", "class_video_1_1_vulkan_render_target_allocator.html", "class_video_1_1_vulkan_render_target_allocator" ],
      [ "VulkanShader", "class_video_1_1_vulkan_shader.html", "class_video_1_1_vulkan_shader" ],
      [ "VulkanShaderProgram", "class_video_1_1_vulkan_shader_program.html", "class_video_1_1_vulkan_shader_program" ],
      [ "VulkanTexture", "class_video_1_1_vulkan_texture.html", "class_video_1_1_vulkan_texture" ],
      [ "VulkanVertexDescription", "class_video_1_1_vulkan_vertex_description.html", "class_video_1_1_vulkan_vertex_description" ],
      [ "ZBinning", "class_video_1_1_z_binning.html", "class_video_1_1_z_binning" ]
    ] ],
    [ "ActiveHymn", "class_active_hymn.html", "class_active_hymn" ],
    [ "ComponentContainer", "class_component_container.html", "class_component_container" ],
    [ "DebugDrawingManager", "class_debug_drawing_manager.html", "class_debug_drawing_manager" ],
    [ "Editor", "class_editor.html", "class_editor" ],
    [ "EditorSettings", "class_editor_settings.html", "class_editor_settings" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "GameSettings", "class_game_settings.html", "class_game_settings" ],
    [ "GLTFImporter", "class_g_l_t_f_importer.html", "class_g_l_t_f_importer" ],
    [ "Hub", "class_hub.html", "class_hub" ],
    [ "Input", "class_input.html", "class_input" ],
    [ "InputHandler", "class_input_handler.html", "class_input_handler" ],
    [ "Log", "class_log.html", "class_log" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MousePicking", "class_mouse_picking.html", "class_mouse_picking" ],
    [ "PhysicsManager", "class_physics_manager.html", "class_physics_manager" ],
    [ "ProfilingManager", "class_profiling_manager.html", "class_profiling_manager" ],
    [ "RayIntersection", "class_ray_intersection.html", "class_ray_intersection" ],
    [ "RenderManager", "class_render_manager.html", "class_render_manager" ],
    [ "ResourceList", "class_resource_list.html", "class_resource_list" ],
    [ "ResourceManager", "class_resource_manager.html", "class_resource_manager" ],
    [ "ScriptFile", "class_script_file.html", "class_script_file" ],
    [ "ScriptManager", "class_script_manager.html", "class_script_manager" ],
    [ "Settings", "class_settings.html", "class_settings" ],
    [ "SoundManager", "class_sound_manager.html", "class_sound_manager" ],
    [ "SuperTrigger", "class_super_trigger.html", "class_super_trigger" ],
    [ "TextureAsset", "class_texture_asset.html", "class_texture_asset" ],
    [ "TriggerManager", "class_trigger_manager.html", "class_trigger_manager" ],
    [ "TriggerOnce", "class_trigger_once.html", "class_trigger_once" ],
    [ "TriggerRepeat", "class_trigger_repeat.html", "class_trigger_repeat" ],
    [ "World", "class_world.html", "class_world" ]
];