layout(local_size_x = 6, local_size_y = 1, local_size_z = 1 ) in;

STORAGE_BUFFER_RW
{
    vec4 data[];
} storageBuffer;

vec4 storageData[6] = vec4[](
    vec4(0.0, -0.5, 0.0, 1.0),
    vec4(1.0, 0.0, 0.0, 1.0),
    vec4(0.5, 0.5, 0.0, 1.0),
    vec4(0.0, 1.0, 0.0, 1.0),
    vec4(-0.5, 0.5, 0.0, 1.0),
    vec4(0.0, 0.0, 1.0, 1.0)
);

void main() {
    uint index = gl_GlobalInvocationID.x;
    
    if (index > 5)
        return;

    storageBuffer.data[index] = storageData[index];
}
